package Modules.Model;

import java.util.Date;

public class artical {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column artical.url
     *
     * @mbggenerated Thu Nov 03 16:39:25 CST 2016
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column artical.title
     *
     * @mbggenerated Thu Nov 03 16:39:25 CST 2016
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column artical.author
     *
     * @mbggenerated Thu Nov 03 16:39:25 CST 2016
     */
    private String author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column artical.time
     *
     * @mbggenerated Thu Nov 03 16:39:25 CST 2016
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column artical.keywords
     *
     * @mbggenerated Thu Nov 03 16:39:25 CST 2016
     */
    private String keywords;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column artical.orignalResource
     *
     * @mbggenerated Thu Nov 03 16:39:25 CST 2016
     */
    private String orignalResource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column artical.category
     *
     * @mbggenerated Thu Nov 03 16:39:25 CST 2016
     */
    private String category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column artical.contemt
     *
     * @mbggenerated Thu Nov 03 16:39:25 CST 2016
     */
    private String contemt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column artical.url
     *
     * @return the value of artical.url
     *
     * @mbggenerated Thu Nov 03 16:39:25 CST 2016
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column artical.url
     *
     * @param url the value for artical.url
     *
     * @mbggenerated Thu Nov 03 16:39:25 CST 2016
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column artical.title
     *
     * @return the value of artical.title
     *
     * @mbggenerated Thu Nov 03 16:39:25 CST 2016
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column artical.title
     *
     * @param title the value for artical.title
     *
     * @mbggenerated Thu Nov 03 16:39:25 CST 2016
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column artical.author
     *
     * @return the value of artical.author
     *
     * @mbggenerated Thu Nov 03 16:39:25 CST 2016
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column artical.author
     *
     * @param author the value for artical.author
     *
     * @mbggenerated Thu Nov 03 16:39:25 CST 2016
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column artical.time
     *
     * @return the value of artical.time
     *
     * @mbggenerated Thu Nov 03 16:39:25 CST 2016
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column artical.time
     *
     * @param time the value for artical.time
     *
     * @mbggenerated Thu Nov 03 16:39:25 CST 2016
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column artical.keywords
     *
     * @return the value of artical.keywords
     *
     * @mbggenerated Thu Nov 03 16:39:25 CST 2016
     */
    public String getKeywords() {
        return keywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column artical.keywords
     *
     * @param keywords the value for artical.keywords
     *
     * @mbggenerated Thu Nov 03 16:39:25 CST 2016
     */
    public void setKeywords(String keywords) {
        this.keywords = keywords == null ? null : keywords.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column artical.orignalResource
     *
     * @return the value of artical.orignalResource
     *
     * @mbggenerated Thu Nov 03 16:39:25 CST 2016
     */
    public String getOrignalResource() {
        return orignalResource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column artical.orignalResource
     *
     * @param orignalResource the value for artical.orignalResource
     *
     * @mbggenerated Thu Nov 03 16:39:25 CST 2016
     */
    public void setOrignalResource(String orignalResource) {
        this.orignalResource = orignalResource == null ? null : orignalResource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column artical.category
     *
     * @return the value of artical.category
     *
     * @mbggenerated Thu Nov 03 16:39:25 CST 2016
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column artical.category
     *
     * @param category the value for artical.category
     *
     * @mbggenerated Thu Nov 03 16:39:25 CST 2016
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column artical.contemt
     *
     * @return the value of artical.contemt
     *
     * @mbggenerated Thu Nov 03 16:39:25 CST 2016
     */
    public String getContemt() {
        return contemt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column artical.contemt
     *
     * @param contemt the value for artical.contemt
     *
     * @mbggenerated Thu Nov 03 16:39:25 CST 2016
     */
    public void setContemt(String contemt) {
        this.contemt = contemt == null ? null : contemt.trim();
    }
}