package Modules.DAO;

import Modules.Model.artical;

public interface articalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table artical
     *
     * @mbggenerated Thu Nov 03 16:39:25 CST 2016
     */
    int deleteByPrimaryKey(String url);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table artical
     *
     * @mbggenerated Thu Nov 03 16:39:25 CST 2016
     */
    int insert(artical record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table artical
     *
     * @mbggenerated Thu Nov 03 16:39:25 CST 2016
     */
    int insertSelective(artical record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table artical
     *
     * @mbggenerated Thu Nov 03 16:39:25 CST 2016
     */
    artical selectByPrimaryKey(String url);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table artical
     *
     * @mbggenerated Thu Nov 03 16:39:25 CST 2016
     */
    int updateByPrimaryKeySelective(artical record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table artical
     *
     * @mbggenerated Thu Nov 03 16:39:25 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(artical record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table artical
     *
     * @mbggenerated Thu Nov 03 16:39:25 CST 2016
     */
    int updateByPrimaryKey(artical record);
}